import AppKit
import Carbon.HIToolbox
import KongFetchCore

/// Watches the general pasteboard and feeds new copies into the history.
final class ClipboardMonitor {
    /// Marks pasteboard contents KongFetch itself restored, so they are not recorded again.
    static let restoredMarker = NSPasteboard.PasteboardType("com.kongxiangrui.KongFetch.restored")

    /// Marker types defined at nspasteboard.org and used by password managers.
    private static let skipMarkers: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword", "de.petermaurer.TransientPasteboardType", "com.typeit4me.clipping",
        "Pasteboard generator type", "net.antelle.keeweb"
    ]
    private static let sourceMarker = NSPasteboard.PasteboardType("org.nspasteboard.source")

    let history: ClipboardHistory
    private let preferences: Preferences
    private let pasteboard: NSPasteboard
    private var timer: Timer?
    private var lastChangeCount: Int
    /// Short note about the last skipped or reduced copy, shown in the panel footer.
    private(set) var lastNotice: String?

    init(history: ClipboardHistory, preferences: Preferences, pasteboard: NSPasteboard = .general) {
        self.history = history
        self.preferences = preferences
        self.pasteboard = pasteboard
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        lastChangeCount = pasteboard.changeCount // never record what was copied before starting
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in self?.poll() }
        timer.tolerance = 0.2
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Ignore whatever is on the pasteboard now (used when recording is switched on or resumed).
    func skipCurrentContents() {
        lastChangeCount = pasteboard.changeCount
    }

    func poll() {
        let change = pasteboard.changeCount
        guard change != lastChangeCount else { return }
        lastChangeCount = change
        guard preferences.clipboardEnabled, !preferences.clipboardPaused else { return }

        let types = Set((pasteboard.types ?? []).map(\.rawValue) + (pasteboard.pasteboardItems ?? []).flatMap { $0.types.map(\.rawValue) })
        if types.contains(Self.restoredMarker.rawValue) { return }
        if !types.isDisjoint(with: Self.skipMarkers) || types.contains(where: { $0.lowercased().contains("concealed") }) {
            lastNotice = "跳过了一条标记为机密的内容"
            return
        }

        let source = Self.sourceApplication(pasteboard)
        if let bundleID = source.bundleID?.lowercased(),
           preferences.clipboardExcludedApps.contains(where: { $0.lowercased() == bundleID }) {
            return
        }
        guard let candidate = capture(source: source) else { return }
        // Someone may have copied again while we were reading.
        guard pasteboard.changeCount == change else { return }
        if case .rejected(let reason) = history.insert(candidate) { lastNotice = reason }
    }

    private func capture(source: (bundleID: String?, name: String?)) -> ClipCandidate? {
        func candidate(_ payload: ClipCandidate.Payload) -> ClipCandidate {
            ClipCandidate(payload: payload, sourceBundleID: source.bundleID, sourceName: source.name)
        }

        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            return candidate(.files(urls.map(\.path)))
        }

        let text = pasteboard.string(forType: .string)
        let trimmed = text?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        let imageData = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff)

        // Apps like Excel and Keynote put a picture next to copied text; the text is what was meant.
        // Browsers put a link next to a copied image; there the image is what was meant.
        let textIsOnlyALink = !trimmed.contains(where: \.isWhitespace) &&
            (trimmed.hasPrefix("http://") || trimmed.hasPrefix("https://") || trimmed.hasPrefix("file://") || trimmed.hasPrefix("data:"))
        if let imageData, trimmed.isEmpty || textIsOnlyALink {
            guard let normalized = ImageCodec.normalize(imageData, maximumBytes: history.limits.maximumImageBytes) else {
                lastNotice = "图片无法读取或过大，未记录"
                return nil
            }
            if normalized.reduced { lastNotice = "图片较大，已缩小后保存" }
            return candidate(.image(normalized.data, fileExtension: normalized.fileExtension,
                                    width: normalized.width, height: normalized.height))
        }
        if let text, !trimmed.isEmpty {
            let rtf = pasteboard.data(forType: .rtf)
            return candidate(.text(text, rtf: rtf))
        }
        return nil
    }

    private static func sourceApplication(_ pasteboard: NSPasteboard) -> (bundleID: String?, name: String?) {
        if let declared = pasteboard.string(forType: sourceMarker), !declared.isEmpty {
            let name = NSWorkspace.shared.urlForApplication(withBundleIdentifier: declared)
                .map { (FileManager.default.displayName(atPath: $0.path) as NSString).deletingPathExtension }
            return (declared, name ?? declared)
        }
        let app = NSWorkspace.shared.frontmostApplication
        return (app?.bundleIdentifier, app?.localizedName)
    }

    // MARK: Restoring

    /// Puts an entry back on the pasteboard. Returns false if its data is gone.
    @discardableResult
    func restore(_ item: ClipItem, plainTextOnly: Bool = false) -> Bool {
        let entry = NSPasteboardItem()
        switch item.kind {
        case .text:
            guard let text = item.text else { return false }
            entry.setString(text, forType: .string)
            if !plainTextOnly, let name = item.richTextFile, let rtf = history.store.readBlob(name) {
                entry.setData(rtf, forType: .rtf)
            }
        case .image:
            guard let name = item.imageFile, let data = history.store.readBlob(name) else { return false }
            if name.hasSuffix(".png") {
                entry.setData(data, forType: .png)
            } else {
                entry.setData(data, forType: NSPasteboard.PasteboardType("public.jpeg"))
            }
            // TIFF is the type every AppKit app understands.
            if let tiff = NSImage(data: data)?.tiffRepresentation { entry.setData(tiff, forType: .tiff) }
        case .files:
            let urls = (item.filePaths ?? []).map { URL(fileURLWithPath: $0) }
            guard !urls.isEmpty else { return false }
            pasteboard.clearContents()
            guard pasteboard.writeObjects(urls as [NSURL]) else { return false }
            _ = pasteboard.addTypes([Self.restoredMarker], owner: nil)
            pasteboard.setString("1", forType: Self.restoredMarker)
            lastChangeCount = pasteboard.changeCount
            return true
        }
        entry.setString("1", forType: Self.restoredMarker)
        pasteboard.clearContents()
        let ok = pasteboard.writeObjects([entry])
        lastChangeCount = pasteboard.changeCount
        return ok
    }
}

/// Sends ⌘V to the frontmost app. Needs Accessibility permission.
enum Paster {
    static var isTrusted: Bool { AXIsProcessTrusted() }

    /// Shows the system Accessibility prompt.
    static func requestTrust() {
        let options = [kAXTrustedCheckOptionPrompt.takeUnretainedValue() as String: true] as CFDictionary
        _ = AXIsProcessTrustedWithOptions(options)
    }

    static func openAccessibilitySettings() {
        if let url = URL(string: "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility") {
            NSWorkspace.shared.open(url)
        }
    }

    static func pasteIntoFrontmostApp() {
        let source = CGEventSource(stateID: .combinedSessionState)
        let keyCode = CGKeyCode(kVK_ANSI_V)
        let down = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false)
        down?.flags = .maskCommand
        up?.flags = .maskCommand
        down?.post(tap: .cgAnnotatedSessionEventTap)
        up?.post(tap: .cgAnnotatedSessionEventTap)
    }
}
